### ISSUE TITLE
The Concept - Description

### ISSUE THREAD

**Issue by Hoangi** [pandaaan/kumoon#3]
Our concept "Mây" is a visual workspace in which you can to be creative, create and come together to collaborate with others. This workspace is presented as a room that you can furnish and interact with. The user are visible throught avatars, who display the actions of the user.

**Comment by Hoangi** [comment]
**Brainstorm**
We were thinking about how a cross-border idea might look like and which ideas that already exists might fit the theme. A lot of ideas were related to AR and VR and how conversations often endet with, "but this already exists".
Funnily enough TikTok could be considered cross-border since they combine different art forms of film and music, hence we thought the idea mustn't be truly unique.

**Comment by Hoangi** [comment]
**Project Statement** (WIP)
_Explain why this is a cross-border idea and how it is related to the theme_
The goal is to display and share our work with others. Organize projects for groupworks or alone.

**Comment by hubui** [comment]
**Project Statement (WIP)**
Explain why this is a cross-border idea and how it is related to the theme
May is a visual co-working space designed like a game that especially explores the art of creative writing. The visual elements help to keep the room sorted. If files are created without order, it shows in the room. Additionally, tools to organize projects are available, since the goal is to work collaboratively with others. When we developed this idea, we strongly focussed on the theme "break the creative distance". Although there are many tools to work together online such as dropbox paper, google docs or notion, what we found them to be lacking was the feeling of closeness and presence. Therefore we wanted to enhance what already existed by adding avatars that represent us and a designated and customizeable space to work in. The customisability furthermore allows us to create a work space that we feel comfortable in while creating something that connects all team members.
