### ISSUE TITLE
Our Story - Description

### ISSUE THREAD

**Issue by Hoangi** [pandaaan/kumoon#5]
**Brainstorm**
We were thinking about how a cross-border idea might look like and which ideas that already exists might fit the theme. A lot of ideas were related to AR and VR and how conversations often endet with, "but this already exists".
Funnily enough TikTok could be considered cross-border since they combine different art forms of film and music, hence we thought the idea mustn't be truly unique but still can be innovative.

_Originally posted by @Hoangi in https://github.com/pandaaan/kumoon/issues/3#issuecomment-723473800_

**Comment by Hoangi** [comment]
**Mindplace**

**Digital Workspace**

**Comment by hubui** [comment]
We began our project with questions like how could a cross-border idea look like and which already existing ideas might fit the theme. A lot of early ideas were related to AR and VR, followed by many discussions that ended with "but this already exists". Funnily enough TikTok can be considered a cross-border idea since it combines the two different art forms of film and music. So we came to realize that the idea didn't need to be truly unique yet still could be innovative.
